# Вкл/Выкл использование downloader сервера (актуально если на удаленном хосте нет доступа к сети интернет или же количество хостов на которые необходимо доставить файлы
use_downloader: true
# При использовании downloader в данную папку будет осуществлятся скачивание файлов, в дальнейшем распространение файлов на удаленные хосты осуществляется из данной папки downloader сервера.
downloader_source_folder: ~/DISTR
# Папка в которую будет осуществлена загрузка установочного архива
distribution_path: "/opt/DISTR"

# Устаноавливаемая версия
containerd_version: v1.3.7
# Root директория для компонентов
containerd_bin_path: /usr/local/bin
runc_bin_path: "{{ containerd_bin_path }}"
kata_bin_path: "{{ containerd_bin_path }}"

# Список runtimes для контейнеров
containerd_runtimes:
  - runc
#  - kata

# Имена устанавливаемых компонентов
containerd_bin_name:
  - containerd
  - containerd-shim
  - containerd-shim-runc-v1
  - containerd-shim-runc-v2
  - containerd-stress
  - ctr

# Папка для конфигурационных файлов
containerd_conf_dir: /etc/containerd
# Папка для данных
containerd_data_dir: /var/lib/containerd
# Папка для плагинов
containerd_plugin_dir: /opt/containerd
# Папка для запущенных контейнеров
containerd_state_dir: /run/containerd

# Containerd options
containerd_use_systemd_cgroup: false

containerd:
  v1.3.3:
    source_url: https://github.com/containerd/containerd/releases/download/v1.3.3/containerd-1.3.3.linux-amd64.tar.gz
    # Контрольная сумма скачаемого архива
    checksum_algorithm: "sha256"
    archive_checksum: b76d54ca86b69871266c29d0f1ad56f37892ab4879b82d34909ab94918b83d16
    # Параметр распаковки архива на удаленном сервере
    extra_opts: --strip-components=1
    # Контрольная сумма бинарных файлов
    containerd:
        checksum: b0c2df3e3146d6c53e6097083efc616c475b62ad6a1434a2833d82e7e2434e59
    containerd-shim:  
        checksum: b0677cb7ee299bae38f533391acbc506926fc3b6d6bea8473e8668def6214b63
    containerd-shim-runc-v1:  
        checksum: 38c52fff86401bbb1bd051b5346e3a35fc92c4b0ae9140e647879ad6b3bb3234
    containerd-shim-runc-v2: 
        checksum: 51ff756d1d2b16ad30f158930e9c3deeeabebf23fedefbacf688a69070899791
    containerd-stress:  
        checksum: 721e3895e32ebc426f394e451b40ef4fb9d5adeb0b8d9d1b010b8d7f2c7aa5d8
    ctr:  
        checksum: 9ae0b69747fac3e7d4f1c1ba3f20548348a6acc5d828b54a6a9efc7afcb7f8df  
  v1.3.4:
    source_url: https://github.com/containerd/containerd/releases/download/v1.3.4/containerd-1.3.4.linux-amd64.tar.gz
    # Контрольная сумма скачаемого архива
    checksum_algorithm: "sha256"
    archive_checksum: 61e65c9589e5abfded1daa353e6dfb4b8c2436199bbc5507fc45809a3bb80c1d
    # Параметр распаковки архива на удаленном сервере
    extra_opts: --strip-components=1
    # Контрольная сумма бинарных файлов
    containerd:
        checksum: 7fd17e3814eec5478088b1c312788729394ec4bfdea44dcba7c9c321780e0c39
    containerd-shim:  
        checksum: 9f1b42f721e5bf542b76ec9814c3680de103bf17c064de6043e4133ed0b80874
    containerd-shim-runc-v1:  
        checksum: 8cbb0444b3435e4aa559af8e8223b938c175f5f6e153a01c2f911488ad2e10a5
    containerd-shim-runc-v2: 
        checksum: fb74222b534ab7bebe34b5034673a918603b9d403ceed5ad2e18b8e1b2e64934
    containerd-stress:  
        checksum: cd4d2c036a81740bd19b38bb4a352865df3c0c556b998ea59b6ad36d01f00049
    ctr:  
        checksum: 3f30d53003569acb9ee9796b6b6aae39a54eb46116582e79695230cf5bc6ab0d
  v1.3.6:
    source_url: https://github.com/containerd/containerd/releases/download/v1.3.6/containerd-1.3.6-linux-amd64.tar.gz
    # Контрольная сумма скачаемого архива
    checksum_algorithm: "sha256"
    archive_checksum: 5d5cf1017eb33cfe75e766818cdf94df7df044bd73ace60dbfa8851ed6a7c063
    # Параметр распаковки архива на удаленном сервере
    extra_opts: --strip-components=1
    # Контрольная сумма бинарных файлов
    containerd:
        checksum: c598379af259952611794f6146aceaa911fd08d5494a0475e7237c7f94694c89
    containerd-shim:  
        checksum: fca0fd248954c006eedff41bcafb1bb7deff4698a671a2b95ea12c11ef00256a
    containerd-shim-runc-v1:  
        checksum: 53683011029081b9bf51adfb4e5c0bb8f9237f804dd0cec44d785bcacc744f51
    containerd-shim-runc-v2: 
        checksum: 59c86aa544195b0cb89fdf1e341bd5e60202b54ddef79982740574f208025731
    containerd-stress:  
        checksum: 7c4f7bfe1011ae224a70a53483f48ba4afef85a57c18cc6624c4f829aa6e3d3a
    ctr:  
        checksum: 420d2840e999c38a5e5c96022be4932ad9beac9aca4f9496dfcfd7878604a5ac
  v1.3.7:
    source_url: https://github.com/containerd/containerd/releases/download/v1.3.7/containerd-1.3.7-linux-amd64.tar.gz
    # Контрольная сумма скачаемого архива
    checksum_algorithm: "sha256"
    archive_checksum: 5bfa0524492ec7f3ba96ea91d3b36dfa6b1fa9e38b9d61658df93cd9458b3144
    # Параметр распаковки архива на удаленном сервере
    extra_opts: --strip-components=1
    # Контрольная сумма бинарных файлов
    containerd:
        checksum: 29a0b49db854daa85b53d14af92740ecbab0bed4777b52d304cb4e3c9444fcf5
    containerd-shim:  
        checksum: af5ebee6e9b387920d72ad075e51835f2f3215b3ec407b28491ae7383c283d76
    containerd-shim-runc-v1:  
        checksum: cd180f864905f86f39ee62c2336a9075e4c61cb34a090e26e38f1534be19d852
    containerd-shim-runc-v2: 
        checksum: 512d1520c35ad5e46b3b6e843dcc7ee1012feb0f4863b5b4c27baeb750d37085
    containerd-stress:  
        checksum: 83a498653164dbca3e784cb578220fe4e6051cafb0b5f2b70f763ec6ba79b9b4
    ctr:  
        checksum: 52e39c127ae6d30c50514b263fcdf273a3ccac72356cfc6bfc2da1ca48cf120a
