---
# Перечитываем конфигурацию systemd
- name: CONTAINERD | Reload systemd
  systemd:
    daemon_reload: true

# Перезагружаем сервис
- name: CONTAINERD | Restart containerd
  service:
    name: containerd
    state: restarted
    enabled: true

# Останавливаем сервис
- name: CONTAINERD | Ensure service is stopped
  service:
    name: containerd
    state: stopped
  when: "'containerd.service' in services"