---
galaxy_info:
  author: Kirill Protopopov
  description: Ansible role for installing Containerd

  license: GPLv3

  min_ansible_version: 2.9

  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - cri
    - containerd

dependencies:
  - role: runc
    when:
      - "'runc' in containerd_runtimes"
    tags:
      - cri
      - runc

  - role: cri-tools
    tags:
      - cri
      - cri-tools
