---
name: Molecule Test

on:
  - push

defaults:
  run:
    working-directory: roles/containerd/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: containerd
      - name: molecule
        uses: robertdebock/molecule-action@2.6.1
