---
# Создаем директорю для конфигурационного файла
- name: CONTAINERD | Creating folders
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0711"
  loop:
    - "{{ containerd_conf_dir }}"
    - "{{ containerd_plugin_dir }}"
    - "{{ containerd_state_dir }}"
    - "{{ containerd_data_dir }}"

# Создаем конфигурационный файл systemd сервиса CONTAINERD    
- name: CONTAINERD | Creating containerd.service file
  template:
    src: containerd.service.j2
    dest: /etc/systemd/system/containerd.service
    owner: root
    group: root
    mode: "0644"
  register: containerd_systemd_config

# Создаем конфигурационный файл CONTAINERD
- name: CONTAINERD | Creating configuration file for containerd service
  template:
    src: config.toml.j2
    dest: "{{ containerd_conf_dir }}/config.toml"
    owner: root
    group: root
    mode: "0644"
  register: containerd_config

# Перезагружаем сервис
- name: CONTAINERD | Restart containerd
  systemd:
    name: containerd
    state: restarted
    daemon_reload: true
    enabled: true
  when:
    - "'containerd.service' in services"
    - containerd_config.changed or
      containerd_systemd_config.changed

# Убеждаемся что CONTAINERD сервис запущен и добавлен в автозапуск  
- name: CONTAINERD | Ensure containerd service is started and enabled at boot
  systemd:
    name: containerd
    state: started
    enabled: true
